apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    app: kubeflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-user
  labels:
    app: kubeflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-infrastructure
  labels:
    app: kubeflow
