---
# MinIO API Service (для S3 операций)
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: ml-infrastructure
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
  selector:
    app: minio
---
# MinIO Console Service (веб-интерфейс)
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: ml-infrastructure
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30900
      protocol: TCP
      name: console
  selector:
    app: minio
